---
# Checklist FOOL PROOF

- name: List all buckets
  shell: s3cmd -c /var/tmp/s3cfg ls | awk '{print $3}' | awk -F/ '{print $3}'
  register: s3cmd_out

- name: Debug buckets
  debug: msg="{{ s3cmd_out }}"
  when:
  - debug

- name: Fail if bucket doesnt exist
  fail: msg="FAILED - There is no bucket of the name {{ stack_name }}"
  when:
  - not "{{ stack_name in s3cmd_out.stdout_lines }}"

- name: Checks that the NAT2DNS exists
  shell: aws cloudformation describe-stacks
         --stack-name "{{ stack_name }}"
         --region eucalyptus
         --endpoint-url="http://cloudformation.{{ region_dns }}:8773/"
  tags:
  - cloudformation
  - fool_proof
  register: stacks_list

- name: Set stacks list
  set_fact: stacks="{{ stacks_list.stdout|from_json }}"

- name: Debug stacks length
  debug: msg="{{ stacks.Stacks|length }}"
  when:
  - debug

- name: Stop if no Stack found
  fail: msg="FAILED - There is no stack with the name {{ stack_name }}"
  when:
  - "{{ stacks.Stacks|length != 1 }}"
  tags:
  - fool_proof
  - failed
