---
# Delete the NAT2DNS stack

- name: Template the s3cfg file
  template: src=s3cfg.conf.j2 dest=/var/tmp/s3cfg

- name: Fool proof
  include: checklist.yml

- name:  Init EIPs
  include: init_eips.yml

- name: Parse the stack configuration
  include: parse_config.yml

- name: Set the new EIP configuration
  include: set_eips.yml

- name: Delete the old bucket
  shell: s3cmd -c /var/tmp/s3cfg rb -r "s3://{{ stack_name }}"

- name: Delete the stack
  shell: aws cloudformation delete-stack
         --stack-name "{{ stack_name }}"
         --region eucalyptus
         --endpoint-url="http://cloudformation.{{ region_dns }}:8773/"
