---
# Delete the NAT2DNS stack

- name:  Init EIPs
  include: init_eips.yml

- name: Fool proof
  include: checklist.yml

- name: Parse the stack configuration
  include: parse_config.yml

- name: Set the new EIP configuration
  include: set_eips.yml

- name: Delete the stack
  shell: aws cloudformation delete-stack
         --stack-name "{{ stack_name }}"
         --region eucalyptus
         --endpoint-url="http://cloudformation.{{ region_dns }}:8773/"
