#
# MAIN
#

- name: Pre-Requesites
  include: pre_requesites.yml

- name: Fetch new data
  setup:

- name: Get the instance EC2 info
  action: ec2_facts
  register: ec2_data

- name: EIP
  include: get_addresses.yml
