#
# Get the addresses to use
#

- name: Debug the EIPs
  debug: msg="{{ ec2_eips }}"
  when:
  - debug

- name: Create the asgJLB config file
  template: src=asgJLB.conf.j2 dest=/var/tmp/asgJLB.conf

- name: Create the asgJLB config file
  template: src=asgJLB_target.conf.j2 dest=/var/tmp/asgJLB-target.conf

- name: Push files to the bucket
  s3: bucket="{{ stack_name }}" object="{{ item.split('/') | last }}" src="{{ item }}" mode=put s3_url="{{ api_protocol }}s3.{{ region_dns }}:{{ api_port }}"
  with_items:
  - "/var/tmp/asgJLB.conf"
  - "/var/tmp/asgJLB-target.conf"
