---
# FOOL PROOF

- name: Checks that the NAT2DNS doesnt already exists
  shell: aws cloudformation describe-stacks --stack-name "{{ stack_name }}"
         --region eucalyptus
         --output=json
         --endpoint-url="http://cloudformation.{{ region_dns }}:8773/"
  tags:
  - cloudformation
  - fool_proof
  register: stacks_list

- name: Set stacks list
  set_fact: stacks="{{ stacks_list.stdout|from_json }}"

- name: Debug stacks length
  debug: msg="{{ stacks.Stacks|length }}"
  when:
  - debug

- name: Stop here for now
  fail: msg="FAILED - There is already a stack with the name {{ stack_name }}"
  when:
  - "{{ stacks.Stacks|length > 0 }}"
  tags:
  - fool_proof
  - failed

- name: List all buckets
  shell: s3cmd -c /var/tmp/s3cfg ls | awk '{print $3}' | awk -F/ '{print $3}'
  register: s3cmd_out

- name: Debug buckets
  debug: msg="{{ s3cmd_out }}"
  when:
  - debug

- name: Fail if bucket already exists
  fail: msg="FAILED - There is already a bucket of the name {{ stack_name }}"
  when:
  - "{{ stack_name in s3cmd_out.stdout_lines }}"
