---
# Play to deploy a new NAT Stack
# Remove the ec2Mgmt dependency building all artifacts prior to the CF kick off


- block:
   - template: src=aws_creds.j2 dest=/var/tmp/awsrc
   - template: src=s3cfg.conf.j2 dest=/var/tmp/s3cfg
  rescue:
  - fail: msg="Failed to create initial configuration files"

- name: FOOL PROOF
  include: checklist.yml

- name: Init configuration for the EIPs
  include: init_eips.yml

- name: Set resources configuration
  include: set_resources.yml

- name: Set options together
  set_fact: params="{{ default_params | union(options_params) }}"

- block:
   - include: create_stack.yml
   - include: set_eips.yml
  always:
   - debug: msg="NAT2DNS Creation in {{ region_dns }} with AWS CREDS {{ aws_access_key }}"
