---
# Play to deploy a new NAT Stack
# Remove the ec2Mgmt dependency building all artifacts prior to the CF kick off

- name: FOOL PROOF
  include: checklist.yml

- name: Init configuration for the EIPs
  include: init_eips.yml

- name: Set resources configuration
  include: set_resources.yml

- name: Set the new EIPs configuration
  include: set_eips.yml

- name: Set options together
  set_fact: params="{{ default_params | union(options_params) }}"

- name: Create the parameters config JSON
  template: src=cf_parameters.json.j2 dest=/var/tmp/cf_parameters.json
  tags:
  - cloudformation
  - config

- name: Create the NAT2DNS Stack
  shell: aws cloudformation create-stack --stack-name "{{ stack_name }}"
         --template-url "{{ template_url }}"
         --capabilities CAPABILITY_IAM
         --disable-rollback
         --parameters file:///var/tmp/cf_parameters.json
         --region eucalyptus
         --endpoint-url="http://cloudformation.{{ region_dns }}:8773/"
  tags:
  - cloudformation
  - create
