---
# Play to deploy a new NAT Stack
# Remove the ec2Mgmt dependency building all artifacts prior to the CF kick off

- name: Init configuration for the EIPs
  include: init_eips.yml

- name: FAILED - Not enough EIPs available
  fail: msg="FAILED - Not enough EIPs available"
  when:
  - "{{ eips.stdout_lines | length < 1 }}"

- name: Set resources configuration
  include: set_resources.yml

- name: Set the new EIPs configuration
  include: set_eips.yml

- name: Create the parameters config JSON
  template: src=cf_parameters.json.j2 dest=/var/tmp/cf_parameters.json
  tags:
  - cloudformation
  - config

- name: Create the NAT2DNS Stack
  shell: aws cloudformation create-stack --stack-name "{{ stack_name }}"
         --template-url "{{ template_url }}"
         --capabilities CAPABILITY_IAM
         --disable-rollback
         --parameters file:///var/tmp/cf_parameters.json
         --region eucalyptus
         --endpoint-url="http://cloudformation.{{ region_dns }}:8773/"
  tags:
  - cloudformation

# - name: Describe the addresses available
#   shell: aws ec2 describe-addresses --endpoint-url="{{api_protocol }}ec2.{{ region_dns }}:{{ api_port }}" --output=text --region=eucalyptus | grep -v i\- | awk '{print $3}'
#   register: eips
# Disabled - new version uses the s3 config file to keep track of EIPs
# Would be task #1
