---
# Play to deploy a new NAT Stack
# Remove the ec2Mgmt dependency building all artifacts prior to the CF kick off

- name: Describe the addresses available
  shell: aws ec2 describe-addresses --endpoint-url={{ ec2_url }} --output=text --region=eucalyptus | grep -v i\- | awk '{print $3}'
  register: eips

- name: Set ec2_eips list
  set_fact: ec2_eips="{{ eips.stdout_lines  }}"

- name: Debug ec2_eips
  debug: msg="{{ ec2_eips }}"
  when:
  - debug

- name: Create the ec2Mgmt EIP Config
  include: ec2Mgmt_eip.yml

- name: Create the ec2SFTP EIP Config
  include: ec2SFTP_eip.yml
  when:
  - has_sftp

- name: Create the asgJLB EIP Config
  include: asgJLB_eip.yml
  when:
  - has_elb

- name: Create the parameters config JSON
  template: src=cf_parameters.json.j2 dest=/var/tmp/cf_parameters.json
  tags:
  - cloudformation
  - config

- name: Create the NAT2DNS Stack
  shell: aws cloudformation create-stack --stack-name "{{ stack_name }}"
         --template-url "{{ template_url }}"
         --capabilities CAPABILITY_IAM
         --disable-rollback
         --parameters file:///var/tmp/cf_parameters.json
         --region eucalyptus
         --endpoint-url="http://cloudformation.{{ region_dns }}:8773/"

# - name: Create the stack
#   cloud_formation:
#     ec2_url="{{ ec2_url }}"
#     stack_name="test"
#     state="present"
#     region="eucalyptus"
#     template_url="http://objectstorage.cloud.emea.eucalyptus.com:8773/templates/standalone.json"
#     template_parameters:
#       KeyName="john"
#       ImageId="emi-002fcf91"
#       RegionDNS="cloud.emea.eucalyptus.com"
#       BucketName="devnat3"
# S**T doc for the module. What's the right syntax ????

  # - name: Create the NAT stack bucket
  #   s3_bucket: name="{{ bucket_name }}" state=present ec2_url="{{ ec2_url }}" s3_url="{{ s3_url }}" tags="{{ item }}"
  #   with_items:
  #   - {'stack_name': "{{ stack_name }}" }
  # Cant use because of a py module missing the in module and Euca doesnt support all API calls in this module
