---
# Set the new EIPs configuration in S3

- name: Create the new eips-global.conf file
  template: src=eips-global.conf.j2 dest=/var/tmp/eips-global.conf
  tags:
  - config
  - global

- name: Create the stack EIP configuration
  template: src=stack-eips.conf.j2 dest="/var/tmp/{{ stack_name }}-eips.conf"
  tags:
  - config

- name: Upload the nat2dns config files with timestamps
  s3: bucket="{{ nat2dns_bucket }}"
      object="{{ ansible_date_time.date }}-{{ ansible_date_time.tz }}/{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}/{{ item.split('/') | last }}"
      src="{{ item }}"
      mode=put s3_url="{{ api_protocol }}s3.{{ region_dns }}:{{ api_port }}"
  with_items:
  - "/var/tmp/eips-global.conf"
  - "/var/tmp/{{ stack_name }}-eips.conf"
  tags:
  - config
  - global

- name: Upload the nat2dns config files timestamps
  s3: bucket="{{ nat2dns_bucket }}"
      object="{{ item.split('/') | last }}"
      src="{{ item }}"
      mode=put
      s3_url="{{ api_protocol }}s3.{{ region_dns }}:{{ api_port }}"
  with_items:
  - "/var/tmp/eips-global.conf"
  - "/var/tmp/{{ stack_name }}-eips.conf"
  tags:
  - config
  - global

- name: Upload the stack config in stack bucket
  s3: bucket="{{ stack_name }}"
      object="{{ item.split('/') | last }}"
      src="{{ item }}"
      mode=put
      s3_url="{{ api_protocol }}s3.{{ region_dns }}:{{ api_port }}"
  with_items:
  - "/var/tmp/{{ stack_name }}-eips.conf"
  tags:
  - config
  - global
